# Generated by Django 5.0.7 on 2024-11-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('online delivery', 'Online Delivery')], max_length=20),
        ),
    ]
