# Generated by Django 5.0.7 on 2024-08-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=4100)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name="Keyinroq jo'natish vaqti")),
                ('file_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video')], db_default='text', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('pending', 'Pending'), ('not_sent', 'Not sent')], db_default='pending', max_length=20, verbose_name='Xabarning statusi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Xabar yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Telegram Kanal xabari',
                'verbose_name_plural': 'Telegram kanal xabarlari',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=4100, verbose_name='Xabar')),
                ('content_type', models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], max_length=10)),
                ('seen', models.BooleanField(db_default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
        ),
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Domen Nomi')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=8, verbose_name='Sayt aktiv yoki  aktivmasligi')),
                ('is_configured', models.BooleanField(db_default=True)),
                ('is_sub_domain', models.BooleanField(db_default=True, verbose_name='Sayt domen quygan yoki yuqligi')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Telegram username')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='BotFather dan olingan token')),
                ('group_access_token', models.CharField(max_length=255, unique=True, verbose_name='guruhda ishlashi uchun token')),
                ('is_new_template', models.BooleanField(verbose_name='web app True odiiy bot False')),
                ('order_button_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=255, verbose_name='Telegram kanal username')),
            ],
            options={
                'verbose_name': 'Telegram kanal',
                'verbose_name_plural': 'Telegram kanallar',
            },
        ),
        migrations.CreateModel(
            name='BroadCastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=4100, verbose_name='Xabar')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Lokatsiya lat')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Lokatsiya lon')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name="Keyinroq jo'natish vaqti")),
                ('received_users', models.IntegerField(default=0, verbose_name='Qabul qiluvchilar soni')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('pending', 'Pending'), ('not_sent', 'Not sent')], db_default='pending', max_length=20, verbose_name='Xabarning statusi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'verbose_name': 'Axborotnoma',
                'verbose_name_plural': 'Axborotnomalar',
            },
        ),
    ]
